micronaut:
  application:
    name: mintApp
  server:
    port: 8080
    context-path: /api/v1
    cors:
      enabled: true
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
      jsonschema:
        paths: classpath:META-INF/schemas
        mapping: /schemas/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/mintdb
    driver-class-name: org.postgresql.Driver
    username: mintdb
    password: interview
    db-type: postgres
    dialect: POSTGRES

flyway:
  enabled: true
  migrate-on-start: true
  baseline-on-migrate: true
  out-of-order: true
  locations: classpath:db/migration
  datasources:
    default:
      enabled: true

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true
        format_sql: true

jackson:
  property-naming-strategy: SNAKE_CASE